import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { Theme } from "@radix-ui/themes";
import MainDrawer from "@/components/MainDrawer/MainDrawer";
import { getSession } from "@/server-actions/auth";
import { Toaster } from "sonner";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProvider>
          <Theme accentColor="cyan" className="flex">
            {session && <MainDrawer />}
            <main className="w-screen h-screen geometric-bg">
              {children}
            </main>
            <Toaster richColors />
          </Theme>
        </SessionProvider>
      </body>
    </html>
  );
}
